name: Risk-Aware DevSecOps
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      weight_bugs:
        description: 'Weight for Bugs'
        default: '3'
      weight_vulns:
        description: 'Weight for Vulnerabilities'
        default: '5'
      weight_hotspots:
        description: 'Weight for Hotspots'
        default: '2'
      risk_threshold_low:
        description: 'Low risk ceiling'
        default: '10'
      risk_threshold_med:
        description: 'Medium risk ceiling'
        default: '30'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  devsecops:
    uses: Jubit-Pincy/devsecops-toolkit/.github/workflows/reusable.yml@main
    with:
      sonar_org:                    jubit-pincy
      azure_resource_group:         ''
      azure_api_name:               ''
      azure_webapp_name:            ''
      static_web_app_token_secret:  AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_SEA_01C0BE400
      static_web_app_build_folder:  build
      weight_bugs:                  ${{ github.event.inputs.weight_bugs || '3' }}
      weight_vulns:                 ${{ github.event.inputs.weight_vulns || '5' }}
      weight_hotspots:              ${{ github.event.inputs.weight_hotspots || '2' }}
      risk_threshold_low:           ${{ github.event.inputs.risk_threshold_low || '10' }}
      risk_threshold_med:           ${{ github.event.inputs.risk_threshold_med || '30' }}
    secrets: inherit